title: My Website Title
description: My Website Description
url: https://urvivaidya.github.io

# Build settings
markdown: kramdown
theme: jekyll-theme-hyde
plugins:
  - jekyll-feed

# Navigation
nav:
  - name: Home
    url: /
  - name: Resume
    url: /resume.html
  - name: About
    url: /about.html
  - name: Projects
    url: /projects.html
  - name: Contact
    url: /contact.html

# Social Media Links
social:
  - name: GitHub
    url: https://github.com/urvivaidya
  - name: LinkedIn
    url: https://www.linkedin.com/in/urvi-vaidya

# Exclude files from build process
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
